noticia/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.noticia_list, name='noticia_list'),
    url(r'^posts/(?P<slug>[\w_-]+)/$', views.post, name='post'),
]

sinsermu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^noticia/', include('noticia.urls', namespace='noticia')),
    url(r'^admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

noticia/models.py
#coding=utf-8

from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):

    titulo = models.CharField('Título', max_length=80)
    slug = models.SlugField('Identificador', max_length=100)
    conteudo = models.TextField('Conteúdo')
    criada = models.DateTimeField('Criada em', auto_now_add=True)
    modificada = models.DateTimeField('Modificada em', auto_now=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['titulo']

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('noticia:post', kwargs={'slug': self.slug})
    
        
    
    

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model
from django.contrib import messages


class IndexView(TemplateView):

    template_name = 'index.html'


index = IndexView.as_view()

noticia/views.py
# coding=utf-8

from watson import search as watson

from django.db import models
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Post


class PostListView(generic.ListView):

    template_name = 'noticia/noticia_list.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        queryset = Post.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = watson.filter(queryset, q)
        return queryset


noticia_list = PostListView.as_view()

def post(request, slug):
    post = Post.objects.get(slug=slug)
    context = {
        'post': post
    }

    return render(request, 'noticia/noticia.html', context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}SINSERMU{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">SINSERMU</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="#">Home</a>
						</li>
			<li>
				<a href="#">Diretoria</a>
			</li>

			<li>
				<a href="#">Estatuto</a>
			</li>

			<li>
				<a href="#">Atas de assembléias</a>
			</li>

			<li>
				<a href="#">Inf. financeiras</a>
			</li>

			<li>
				<a href="#">Ofícios</a>
			</li>

			<li>
				<a href="{% url 'noticia:noticia_list' %}">Notícias</a>
			</li>

			<li>
				<a href="#">Convênios</a>
			</li>
		</ul>
	</div>
	</div>
	</div>
    <div class="container margin-top">
		{% block messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }}">
			{{ message }}
		</div>
		{% endfor %}
		{% endblock %}
		{% block container %}{% endblock %}
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
	{% block scripts %}{% endblock %}
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>SINSERMU</h1>
  <p>SINSERMU
</p>
  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
          <ul class="pagination">
              {% for page in paginator.page_range %}
              <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
              {% endfor %}
          </ul>
        </nav>
    </div>
</div>

noticia/templates/noticia/_noticia.html
<div class="col-sm-6 col-md-4">
        <div class="caption">
            <h3>{{ post }}</h3>
            {{ post.conteudo|linebreaks }}
            <p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a>
            </p>
        </div>
</div>

noticia/templates/noticia/noticia.html
{% extends "base.html" %}

{% block title %}
    {{ post }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ post }}</h1>
</div>
<div class="row">
  <div class="col-sm-8">
      {{ post.conteudo|linebreaks }}
  </div>
</div>
{% endblock %}

noticia/templates/noticia/noticia_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Notícias | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Notícias</h1>
</div>
<div class="row">
    {% for post in posts %}
    {% include "noticia/_noticia.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(function(){
    $('.cart-item-add').on('click', function(e){
        e.preventDefault();
        $.ajax({
            url: $(this).attr('href'),
            dataType: 'json',
            success: function(data, textStatus, jqXHR){
                alert(data.message);
            }
        });
    });
});
</script>
{% endblock %}